// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210729145256_Property")]
    partial class Property
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<float>("DownPayment")
                        .HasColumnType("REAL");

                    b.Property<float>("InterestRate")
                        .HasColumnType("REAL");

                    b.Property<int>("ListPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListingUrl")
                        .HasColumnType("TEXT");

                    b.Property<float>("NetIncome")
                        .HasColumnType("REAL");

                    b.Property<int>("NightlyRate")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Occupancy")
                        .HasColumnType("REAL");

                    b.Property<int>("RenovationFurnitureCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilitiesEtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
